export const env = {
  PORT: Number(process.env.REACT_APP_PORT) || 5000,
  USER_SERVICE_URL: process.env.REACT_APP_USER_SERVICE_URL || "",
  POST_SERVICE_URL: process.env.REACT_APP_POST_SERVICE_URL || "",
  GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID || "",
  GOOGLE_CLIENT_SECRETE: process.env.REACT_APP_GOOGLE_CLIENT_SECRETE || "",
  GOOGLE_REDIRECT_URL: process.env.REACT_APP_GOOGLE_REDIRECT_URL || "",
};
