name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          ECR_URL="$ECR_REGISTRY/${{ vars.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $ECR_URL .
          docker push $ECR_URL
          echo "image=$ECR_URL" >> $GITHUB_OUTPUT

      - name: Render new task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: taskdef.json
          container-name: ${{ vars.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Register ECS task definition
        id: register-task
        run: |
          TASK_DEF_JSON=$(cat "${{ steps.task-def.outputs.task-definition }}")
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json "$TASK_DEF_JSON" \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          
      - name: Create ECS CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ vars.CODEDEPLOY_APP }} \
            --deployment-group-name ${{ vars.CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --revision revisionType=AppSpecContent,appSpecContent="{\"version\":\"0.0\",\"Resources\":[{\"TargetService\":{\"Type\":\"AWS::ECS::Service\",\"Properties\":{\"TaskDefinition\":\"${{ steps.register-task.outputs.task_definition_arn }}\",\"LoadBalancerInfo\":{\"ContainerName\":\"${{ vars.CONTAINER_NAME }}\",\"ContainerPort\":80}}}}]}"
